// AUTO-GENERATED by setup-locale-routing.mjs — do not edit by hand.
// Clean-URL language routing + /go affiliate redirect.
export const config = { matcher: ['/', '/go'] };

const GO_URL = "https://spinbao.com/r/7fde107cce49?utm_source=seo&utm_medium=landing&utm_campaign=traffic&utm_content=organic";
const LOCALES = ["no"];

function pickLocale(al) {
  if (!al) return null;
  const ranked = al
    .split(',')
    .map((part) => {
      const [tag, q] = part.trim().split(';q=');
      return { lang: (tag || '').toLowerCase().split('-')[0], q: q ? parseFloat(q) : 1 };
    })
    .sort((a, b) => b.q - a.q);
  for (const { lang } of ranked) if (LOCALES.includes(lang)) return lang;
  return null;
}

export default function middleware(request) {
  const url = new URL(request.url);

  if (url.pathname === '/go') {
    const dest = new URL(GO_URL);
    url.searchParams.forEach((v, k) => dest.searchParams.set(k, v));
    return new Response(null, { status: 302, headers: { Location: dest.toString() } });
  }

  const override = url.searchParams.get('lang');
  const locale =
    override != null
      ? (LOCALES.includes(override) ? override : 'default')
      : (pickLocale(request.headers.get('accept-language')) || 'default');

  url.pathname = '/' + locale + '/index.html';
  return new Response(null, { headers: { 'x-middleware-rewrite': url.toString() } });
}
