// AUTO-GENERATED by setup-locale-routing.mjs — do not edit by hand.
// Clean-URL language routing. Runs only on the document entry ('/').
// Picks a locale from Accept-Language (else 'default') and rewrites '/' to it.
export const config = { matcher: '/' };

const LOCALES = ["es","gr"]; // non-default locales that exist

function pickLocale(al) {
  if (!al) return null;
  const ranked = al
    .split(',')
    .map((part) => {
      const [tag, q] = part.trim().split(';q=');
      return { lang: (tag || '').toLowerCase().split('-')[0], q: q ? parseFloat(q) : 1 };
    })
    .sort((a, b) => b.q - a.q);
  for (const { lang } of ranked) if (LOCALES.includes(lang)) return lang;
  return null;
}

export default function middleware(request) {
  const url = new URL(request.url);
  const override = url.searchParams.get('lang');
  let locale =
    override != null
      ? (LOCALES.includes(override) ? override : 'default')
      : (pickLocale(request.headers.get('accept-language')) || 'default');

  url.pathname = '/' + locale + '/index.html';
  return new Response(null, { headers: { 'x-middleware-rewrite': url.toString() } });
}
